#!/usr/bin/env python
# encoding: utf-8

import json
import argparse
from chef import ChefAPI, autoconfigure

ALLOWED_ACTIONS = ['get', 'delete']

ARGS_PARAMETERS = {
    "get": {"choices": ['clients']},
    "delete": {"choices": ['client']}
}

API = ChefAPI.from_config_file('conf')


class DefaultObject(argparse.Action):

    def __call__(self, parser, namespace, values, option_string=None):

        if namespace.action == 'get':
            print json.dumps(API.api_request('GET', '/clients').keys(), indent=4)
        elif namespace.action == 'delete':
            if getattr(namespace, 'name', None):
                response = API.api_request('DELETE', '/clients/%s' %namespace.name)



if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('action', choices=ALLOWED_ACTIONS)
    known, unknown = parser.parse_known_args()
    parser.add_argument(
            'object',
            action=DefaultObject,
            **ARGS_PARAMETERS[known.action])
    if known.action == 'delete':
        clients = API.api_request('GET', '/clients').keys()
        parser.add_argument('name', choices=clients)
    args = parser.parse_args()
